apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-a-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-a-23
  template:
    metadata:
      labels:
        app: devops-a-23
    spec:
      containers:
        - name: devops-a-23
          image: devops-a-23:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80